import { makeStyles, shorthands, tokens } from "@fluentui/react-components";

const typingBounce = {
	"0%, 80%, 100%": {
		transform: "scale(0.6)",
		opacity: "0.5",
	},
	"40%": {
		transform: "scale(1)",
		opacity: "1",
	},
};

export const useAIAssistantStyles = makeStyles({
	/* ── Root layout ── */
	root: {
		display: "flex",
		flexDirection: "column",
		flex: 1,
		height: "100%",
		width: "100%",
		minHeight: 0,
		backgroundColor: "var(--agent-chat-bg)",
		color: "var(--agent-chat-fg)",
		overflow: "hidden",
	},
	rootFullScreen: {
		position: "absolute",
		top: 0,
		left: 0,
		right: 0,
		bottom: 0,
		zIndex: 10,
	},
	/* Full-screen: sidebar + content in a row */
	immersiveLayout: {
		display: "flex",
		flexDirection: "row",
		flex: 1,
		minHeight: 0,
		overflow: "hidden",
	},
	contentBody: {
		flex: 1,
		display: "flex",
		flexDirection: "column",
		minWidth: 0,
		minHeight: 0,
		height: "100%",
		overflow: "hidden",
	},

	/* ── Sidebar (full-screen only) ── */
	sidebar: {
		display: "flex",
		flexDirection: "column",
		height: "100%",
		backgroundColor: "var(--agent-chat-sidebar-bg, var(--agent-chat-bg))",
		...shorthands.borderRight("1px", "solid", "var(--agent-chat-border)"),
		boxSizing: "border-box",
		flexShrink: 0,
		transitionProperty: "width",
		transitionDuration: "0.2s",
		transitionTimingFunction: "ease",
		overflow: "hidden",
	},
	sidebarExpanded: {
		width: "220px",
	},
	sidebarCollapsed: {
		width: "44px",
	},
	sidebarTopBar: {
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		height: "42px",
		...shorthands.padding("0", "6px"),
		boxSizing: "border-box",
		flexShrink: 0,
	},
	sidebarTopBarExpanded: {
		justifyContent: "space-between",
	},
	sidebarToggle: {
		minWidth: "32px",
		width: "32px",
		height: "32px",
		...shorthands.border("none"),
		...shorthands.borderRadius("8px"),
		...shorthands.padding("0"),
		display: "inline-flex",
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: "transparent",
		color: "var(--agent-chat-muted)",
		cursor: "pointer",
		":hover": {
			backgroundColor: "var(--agent-chat-hover)",
			color: "var(--agent-chat-fg)",
		},
	},
	sidebarNav: {
		display: "flex",
		flexDirection: "column",
		...shorthands.gap("2px"),
		...shorthands.padding("4px", "6px"),
		flex: 1,
		overflowY: "auto",
		overflowX: "hidden",
	},
	sidebarNavButton: {
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		...shorthands.gap("10px"),
		...shorthands.padding("8px"),
		...shorthands.border("none"),
		...shorthands.borderRadius("10px"),
		backgroundColor: "transparent",
		color: "var(--agent-chat-fg)",
		cursor: "pointer",
		fontSize: tokens.fontSizeBase200,
		fontWeight: tokens.fontWeightRegular,
		whiteSpace: "nowrap",
		overflow: "hidden",
		minHeight: "36px",
		":hover": {
			backgroundColor: "var(--agent-chat-hover)",
		},
	},
	sidebarNavButtonExpanded: {
		justifyContent: "flex-start",
		...shorthands.padding("8px", "10px"),
	},
	sidebarNavButtonActive: {
		backgroundColor: "var(--agent-chat-hover)",
		fontWeight: tokens.fontWeightSemibold,
		boxShadow: "inset 0 0 0 1px var(--agent-chat-border)",
	},
	sidebarNavIcon: {
		flexShrink: 0,
		display: "inline-flex",
		alignItems: "center",
		justifyContent: "center",
		width: "20px",
		height: "20px",
		color: "var(--agent-chat-muted)",
	},
	sidebarNavLabel: {
		overflow: "hidden",
		textOverflow: "ellipsis",
	},

	/* ── Header bar ── */
	header: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		height: "42px",
		...shorthands.borderBottom("1px", "solid", "var(--agent-chat-border)"),
		...shorthands.padding("0", "8px"),
		boxSizing: "border-box",
		flexShrink: 0,
	},
	headerTitle: {
		fontSize: tokens.fontSizeBase300,
		fontWeight: tokens.fontWeightSemibold,
		color: "var(--agent-chat-fg)",
		whiteSpace: "nowrap",
		overflow: "hidden",
		textOverflow: "ellipsis",
		minWidth: 0,
		marginLeft: "4px",
	},
	headerActions: {
		display: "flex",
		alignItems: "center",
		...shorthands.gap("2px"),
	},
	headerButton: {
		minWidth: "34px",
		width: "34px",
		height: "34px",
		...shorthands.border("none"),
		...shorthands.borderRadius("50%"),
		...shorthands.padding("0"),
		display: "inline-flex",
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: "transparent",
		color: "var(--agent-chat-muted)",
		cursor: "pointer",
		":hover": {
			backgroundColor: "var(--agent-chat-hover)",
			color: "var(--agent-chat-fg)",
		},
	},
	headerButtonActive: {
		backgroundColor: "var(--agent-chat-hover)",
		color: "var(--agent-chat-brand)",
	},

	/* ── Welcome screen ── */
	welcomeContainer: {
		flex: 1,
		width: "100%",
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		justifyContent: "center",
		...shorthands.gap("24px"),
		...shorthands.padding("24px", "16px", "32px"),
		boxSizing: "border-box",
	},
	welcomeHeading: {
		marginTop: 0,
		marginBottom: 0,
		textAlign: "center",
		fontSize: "34px",
		lineHeight: "1.22",
		fontWeight: tokens.fontWeightRegular,
		color: "var(--agent-chat-muted)",
		letterSpacing: "-0.01em",
		"@media (max-width: 900px)": {
			fontSize: "28px",
		},
		"@media (max-width: 640px)": {
			fontSize: "24px",
		},
	},
	welcomeHeadingStrong: {
		fontWeight: tokens.fontWeightSemibold,
		color: "var(--agent-chat-fg)",
		marginRight: "8px",
	},
	welcomeComposerContainer: {
		width: "100%",
		maxWidth: "980px",
		alignSelf: "center",
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		...shorthands.gap("18px"),
		...shorthands.padding("0", "12px", "24px"),
		boxSizing: "border-box",
	},

	/* ── Thread / message list ── */
	thread: {
		flex: 1,
		minHeight: 0,
		overflowY: "auto",
		overflowX: "hidden",
		width: "100%",
		maxWidth: "920px",
		alignSelf: "center",
		...shorthands.padding("20px", "24px", "12px"),
		boxSizing: "border-box",
		display: "flex",
		flexDirection: "column",
		...shorthands.gap("18px"),
	},

	/* ── User message ── */
	userBlock: {
		display: "flex",
		flexDirection: "column",
		alignItems: "flex-end",
		...shorthands.gap("4px"),
	},
	userTime: {
		fontSize: tokens.fontSizeBase100,
		color: "var(--agent-chat-muted)",
	},
	userBubble: {
		maxWidth: "86%",
		backgroundColor: "var(--agent-chat-brand)",
		color: "var(--agent-chat-user-fg)",
		...shorthands.padding("10px", "16px"),
		...shorthands.borderRadius("16px", "16px", "4px", "16px"),
		fontSize: tokens.fontSizeBase300,
		lineHeight: tokens.lineHeightBase300,
		fontWeight: tokens.fontWeightRegular,
		overflowWrap: "break-word",
		wordBreak: "break-word",
		boxSizing: "border-box",
	},

	/* ── Assistant message ── */
	assistantBlock: {
		display: "flex",
		flexDirection: "column",
		alignItems: "flex-start",
		...shorthands.gap("6px"),
	},
	assistantPreamble: {
		display: "flex",
		alignItems: "center",
		...shorthands.gap("8px"),
		color: "var(--agent-chat-muted)",
		fontSize: tokens.fontSizeBase100,
	},
	avatar: {
		width: "32px",
		height: "32px",
		borderRadius: "50%",
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		backgroundImage: "linear-gradient(135deg, #3367d6 0%, #5f4dd0 100%)",
		color: "#ffffff",
		flexShrink: 0,
	},
	assistantCard: {
		width: "calc(100% - 40px)",
		marginLeft: "40px",
		backgroundColor: "var(--agent-chat-card)",
		...shorthands.border("1px", "solid", "var(--agent-chat-border)"),
		...shorthands.borderRadius("4px", "16px", "16px", "16px"),
		...shorthands.padding("12px", "16px"),
		boxSizing: "border-box",
	},
	assistantBubble: {
		maxWidth: "calc(100% - 40px)",
		marginLeft: "40px",
		backgroundColor: "var(--agent-chat-surface)",
		color: "var(--agent-chat-fg)",
		...shorthands.border("1px", "solid", "var(--agent-chat-border)"),
		...shorthands.borderRadius("4px", "16px", "16px", "16px"),
		...shorthands.padding("10px", "16px"),
		fontSize: tokens.fontSizeBase300,
		lineHeight: tokens.lineHeightBase300,
		whiteSpace: "pre-wrap",
		overflowWrap: "break-word",
		wordBreak: "break-word",
		boxSizing: "border-box",
	},

	/* ── Error message ── */
	errorText: {
		color: "var(--colorPaletteRedForeground1, #c4314b)",
		fontSize: "0.88rem",
	},

	/* ── Typing indicator ── */
	typingIndicator: {
		display: "inline-flex",
		alignItems: "center",
		...shorthands.gap("6px"),
	},
	typingDot: {
		width: "6px",
		height: "6px",
		borderRadius: "50%",
		backgroundColor: "var(--agent-chat-brand)",
		animationName: typingBounce,
		animationDuration: "1.4s",
		animationTimingFunction: "ease-in-out",
		animationIterationCount: "infinite",
		animationFillMode: "both",
	},
	typingDot1: {
		animationDelay: "0s",
	},
	typingDot2: {
		animationDelay: "0.16s",
	},
	typingDot3: {
		animationDelay: "0.32s",
	},

	/* ── Composer / input ── */
	composerContainer: {
		width: "100%",
		maxWidth: "920px",
		alignSelf: "center",
		...shorthands.padding("4px", "12px", "18px"),
		boxSizing: "border-box",
		flexShrink: 0,
	},
	composer: {
		display: "flex",
		flexDirection: "column",
		...shorthands.border("1px", "solid", "var(--agent-chat-border)"),
		...shorthands.borderRadius("16px"),
		backgroundColor: "var(--agent-chat-card)",
		...shorthands.padding("12px", "12px", "8px"),
		boxShadow: tokens.shadow8,
		transitionProperty: "box-shadow",
		transitionDuration: "0.2s",
		":focus-within": {
			...shorthands.border("1px", "solid", "var(--agent-chat-brand)"),
			boxShadow: tokens.shadow16,
		},
	},
	composerInput: {
		width: "100%",
		border: "none",
		outlineStyle: "none",
		resize: "none" as const,
		backgroundColor: "transparent",
		color: "var(--agent-chat-fg)",
		fontFamily: tokens.fontFamilyBase,
		fontSize: tokens.fontSizeBase300,
		lineHeight: tokens.lineHeightBase300,
		minHeight: "28px",
		maxHeight: "120px",
		paddingRight: "4px",
		"::placeholder": {
			color: "var(--agent-chat-muted)",
		},
	},
	composerFooter: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		...shorthands.gap("8px"),
	},
	leftTools: {
		display: "flex",
		alignItems: "center",
		...shorthands.gap("4px"),
		minWidth: 0,
	},
	iconButton: {
		minWidth: "34px",
		width: "34px",
		height: "34px",
		...shorthands.borderRadius("50%"),
		...shorthands.padding("0"),
		...shorthands.border("none"),
		backgroundColor: "transparent",
		color: "var(--agent-chat-muted)",
		cursor: "pointer",
		display: "inline-flex",
		alignItems: "center",
		justifyContent: "center",
		":hover": {
			backgroundColor: "var(--agent-chat-hover)",
			color: "var(--agent-chat-fg)",
		},
	},
	rightTools: {
		display: "flex",
		alignItems: "center",
		...shorthands.gap("6px"),
	},
	sendButton: {
		minWidth: "36px",
		width: "36px",
		height: "36px",
		...shorthands.borderRadius("50%"),
		...shorthands.padding("0"),
		...shorthands.border("none"),
		backgroundColor: "transparent",
		color: "var(--agent-chat-muted)",
		cursor: "pointer",
		display: "inline-flex",
		alignItems: "center",
		justifyContent: "center",
	},
	sendButtonActive: {
		color: "#ffffff",
		backgroundColor: "var(--agent-chat-brand)",
		":hover": {
			backgroundColor: "#0c5da5",
			color: "#ffffff",
		},
	},
});
